### ISSUE TITLE
github sample fails to compile

### ISSUE THREAD

**Issue by ydax** [gsuitedevs/add-ons-samples#39]
Howdy. I'm not able to replicate the github project. When I attempt to run npm build, I get the following error:
`
FunkBook-Pro:github pdavisjones$ npm run build

> github-gmail-add-on-sample@1.0.0 build /Users/pdavisjones/Documents/Coding/apps-script/gmail-add-ons-samples/github
> gulp

fs.js:25
'use strict';
^

ReferenceError: internalBinding is not defined
    at fs.js:25:1
    at req_ (/Users/pdavisjones/Documents/Coding/apps-script/gmail-add-ons-samples/github/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/Users/pdavisjones/Documents/Coding/apps-script/gmail-add-ons-samples/github/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/Users/pdavisjones/Documents/Coding/apps-script/gmail-add-ons-samples/github/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! github-gmail-add-on-sample@1.0.0 build: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the github-gmail-add-on-sample@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pdavisjones/.npm/_logs/2019-05-16T20_48_36_612Z-debug.log
`

**Comment by sqrrrl** [comment]
What version of node are you using?

**Comment by sqrrrl** [comment]
Looks related to https://github.com/gulpjs/gulp/issues/2246 and just verified workaround there works. I'll take a look at updating the dependencies shortly.

Until then, this should work on Node 11+:

```
npm install
npm install natives@1.1.6
npm run build
```

**Comment by pdavisjones** [comment]
Thanks, Steve. I'll try to replicate steps with the workaround on my end.

**Comment by pdavisjones** [comment]
Totally works. Thanks! 👍

**Comment by sqrrrl** [comment]
Reopening to track fixing this in package.json
